image: node:lts

cache:
  paths:
    - $CI_PROJECT_DIR/node_modules/
    - $CI_PROJECT_DIR/packages/**/lib
    - $CI_PROJECT_DIR/configs/**/lib
    - .yarn

stages:
  - CI
  - CD

before_script:
  - yarn

test:
  stage: CI
  tags:
    - scaled
  only:
    - mainline
    - next
    - beta
    - alpha
    - merge_request
  script:
    - yarn test
  artifacts:
    reports:
      cobertura: coverage/cobertura-coverage.xml

lint:
  stage: CI
  tags:
    - scaled
  only:
    - mainline
    - next
    - beta
    - alpha
    - merge_request
  script:
    - yarn lint

build:
  stage: CI
  tags:
    - scaled
  only:
    - mainline
    - next
    - beta
    - alpha
    - merge_request
  script:
    - yarn build

release:
  stage: CD
  tags:
    - scaled
  only:
    - mainline
    - next
    - beta
    - alpha
  script:
    - yarn release
