/**
 * @file app-token.js
 *
 * This is an auto generated token for app authentication. Any changes here will
 * be overridden. However, if you wish to set the app token manually modify the
 * plugin configuration in the `plugin.json`.
 * Check the documentation for more information.
 *
 * Generated by the converse-cli tool for use with the Converse AI
 * Plugins SDK. https://developers.converse.ai/
 *
 * IMPORTANT: THIS FILE IS AUTO GENERATED, CHANGES MAY BE OVERRIDDEN!
 */

module.exports = 'c3b3d240-59c6-11ea-b4d8-5de75a24c881';
